### ISSUE TITLE
target assembly:assembly is case sensitive

### ISSUE THREAD

**Issue by oscarpicas** [senbox-org/snap#1]
the target assembly:assembly is case sensitive:

assembly configuration files: snap-config/main/assembly/*.xml
include the following file name in lowercase: readme.md

this generates the following error in our jenkins build:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:assembly (default-cli) on project snap: Failed to create assembly: Error filtering file '/var/lib/jenkins/jobs/SNAP/workspace/snap/readme.md': /var/lib/jenkins/jobs/SNAP/workspace/snap/readme.md (No such file or directory) -> [Help 1]

changing the name to README.md fixes the issue.

**Comment by marpet** [comment]
This is a dead end project. Will not fix this issue.
