### ISSUE TITLE
DuplicateProjectException

### ISSUE THREAD

**Issue by GerardoLopez** [senbox-org/snap#3]
When compiling under Mac OS X 10.7.5 using Apache Maven 3.2.5:

[ERROR] Project 'org.esa.snap:snap-launcher:2.0.0-SNAPSHOT' is duplicated in the reactor -> [Help 1]

**Comment by marpet** [comment]
Did you follow the steps in https://github.com/senbox-org/snap/blob/master/README.md? Probably you did. Unfortunately it is outdated. I try to update it soon.

**Comment by GerardoLopez** [comment]
Yes I did. About the update, I'm looking forward to getting it.

**Comment by marpet** [comment]
Try to follow this one: https://github.com/senbox-org/snap-engine/blob/master/README.md 
I haven't yet validated it step by step. But it should be right. A colleague want's to test it tomorrow.

**Comment by marpet** [comment]
This is a dead end project. Will not fix this issue.

**Comment by forman** [comment]
We should remove the project soon. Change README.md to say that the source is not in use.
