### ISSUE TITLE
Missing artifact com.oracle:tools:jar:1.8.0 (Windows 7)

### ISSUE THREAD

**Issue by vfdev-5** [senbox-org/snap#4]
Dear developers

Importing the project into Eclipse, building ends up with the message "Missing artifact com.oracle:tools:jar:1.8.0" for the module snap-gpf. Can you, please, provide a solution to this issue.

Cheers

**Comment by marpet** [comment]
Hi, do you have an Oracle SDK installed? This is recommended, we have already experienced some problems with OpenJDK.
However It would be good if you report such problems in our [forum](http://forum.step.esa.int/)

**Comment by vfdev-5** [comment]
Hi, yes I have jdk and JAVA_HOME properly setup. The problem is with maven variable java.home that points to an external jre and not to jdk. I agree that it is not SNAP's problem. I close this issue.
